### ISSUE TITLE
Chat plugin: create a plugin to each engine

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/abi#11]
As a user, I want to be able to use the chat plugins availables on a specific engine (#market place)

**Comment by Dr0p42** [comment]
Hello @FlorentLvr , yes sure it make sense 👍 when this is merged I will update ABI install to run thoses notebooks as well

**Comment by FlorentLvr** [comment]
Done @Dr0p42 ! In each engine, you find a file that you need to run `__plugin__.ipynb`. Let me know if there is any issues: 

![Image](https://github.com/jupyter-naas/abi/assets/48032461/8479ad22-467e-43f6-a1da-64ff2d3e45dc)

**Comment by Dr0p42** [comment]
> Done @Dr0p42 ! In each engine, you find a file that you need to run `__plugin__.ipynb`. Let me know if there is any issues:
> 
> ![Image](https://user-images.githubusercontent.com/48032461/276626669-8479ad22-467e-43f6-a1da-64ff2d3e45dc.png)

Ok this seems good, I think that I will glob to run all __plugin__ automatically, does that sounds good?
