### ISSUE TITLE
As a user, I would like to receive more humans ABI Assistants emails 

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/abi#149]
Certainly! Here's a text revision for the slide that maintains the same professional and engaging vibe:

📊 Content Assistant: Chat Interactions

Hi Jérémy,

I hope this email finds you well. Here is the latest update on your content performance.

Overview
Visualize your content reach by day over the last 2 weeks. Direct access to your content published allows for a nuanced understanding of engagement trends.

Content published this week:

[Brief overview of the content published, with a focus on high points or areas for improvement]
Performance
Follow your KPIs and compare week-over-week statistics:

Views: [Number/% change]
Likes: [Number/% change]
Comments: [Number/% change]
Shares: [Number/% change]
I'm here to support you in optimizing your content strategy and achieving your goals. If you would like to discuss any specific ideas or strategies, I am available for a chat at your convenience.

Take Action:

Track: Monitor the reach of your content and observe your audience's growth.
Communicate: Simplify reporting to your management with clear metrics.
Motivate: Stay inspired to consistently create and post engaging content.
Chat Interactions
Engage with your data to analyze the highs and lows of your content performance.

Access Raw Data
Review the details in your Google Sheets for in-depth analysis.

Let's keep the momentum going!

[Start Chatting Button]

**Comment by jravenel** [comment]
To be reworked differently IMO @FlorentLvr will push it back to Backlog so we can have time sitting on it.
