### ISSUE TITLE
Providing explanation of .env variables

### ISSUE THREAD

**Issue by achiminator** [jupyter-naas/abi#230]
Hey there,
I tried to start your services without all having the environment variables set (only the open ai key). I get the following return value when running `docker compose up`:
```
abi-1  | Run `poetry install` to resolve and get rid of this message.                                                                                                                                                         
abi-1  | 
abi-1  | Traceback (most recent call last):                                                                                                                                                                                   
abi-1  |   File "<string>", line 1, in <module>
abi-1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                                                                                  
abi-1  |     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                      
abi-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
abi-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                 
abi-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                                                                                                                         
abi-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                                                                                       
abi-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
abi-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                 
abi-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                                                                                                                         
abi-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                                                                                       
abi-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
abi-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
abi-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
abi-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
abi-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
abi-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
abi-1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
abi-1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
abi-1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
abi-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
abi-1  |   File "/app/src/__init__.py", line 1, in <module>
abi-1  |     from abi.services.secret.Secret import Secret
abi-1  | ModuleNotFoundError: No module named 'abi'
abi-1 exited with code 1
```
While I think the most apparent suspicion is the missing environment variables, then this error could (1.) potentially produce a more helpful message and (2.) your `.env`-variable contains a lot of environment variables that honestly seem to be somewhat optional (LinkedIn, github). I also do not have all the services (e.g., Hubspot, Stripe). This is potentially mainly a documentation issue, knowing what is a **must** and what is a **optional** value.

**Comment by Dr0p42** [comment]
Hello @achiminator, thank you for trying our project. I updated the `.env.example` to explain a bit more and also comment everything that is optional.

I tried to setup the project from scratch again, just putting an openai api key and it worked for me.

To run the project, you must run `make chat` once you cloned the repo and copied/edited the `.env`

Let me know how it goes please.

**Comment by FlorentLvr** [comment]
@achiminator, Have you been able to follow the procedure from @Dr0p42? Is it working on your side now?

**Comment by achiminator** [comment]
Hey @all, sorry for taking so long. I finally got it up and running. I first ran into the following problem:

```
[+] Building 0.0s (0/0)  docker:default
[+] Building 1.8s (5/9)                                                                                         docker:default
 => [abi internal] load build definition from Dockerfile                                                                  0.0s
 => => transferring dockerfile: 205B                                                                                      0.0s
 => [abi internal] load metadata for docker.io/library/python:3.9                                                         0.6s
 => [abi internal] load .dockerignore                                                                                     0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [abi 1/5] FROM docker.io/library/python:3.9@sha256:dd8b65c39a729f946398d2e03a3e6defc8c0cfec409b9f536200634ad6408b54   0.0s
 => ERROR [abi internal] load build context                                                                               1.1s
 => => transferring context: 57.28MB                                                                                      1.1s
------
 > [abi internal] load build context:
------
failed to solve: archive/tar: unknown file mode ?rwxr-xr-x
```


I was able to solve it using the last comment of https://stackoverflow.com/questions/78523506/docker-error-failed-to-solve-archive-tar-unknown-file-mode-rwxr-xr-x - I needed to delete the automatically created .venv folder after every previous docker build. Maybe that is something that can be done automatically.

Unfortunately, I ran into a different challenge.
```
 ✔ Network 2608naasabi_default  Created                                                                         0.0s 
 ✔ Container 2608naasabi-abi-1  Created                                                                         0.0s 
Attaching to abi-1
abi-1  | Creating virtualenv src in /app/.venv
abi-1  | Command not found: chat-single-assistant
abi-1 exited with code 1
```
Any ideas on where it goes of?

**Comment by FlorentLvr** [comment]
> Hey @ALL, sorry for taking so long. I finally got it up and running. I first ran into the following problem:
> 
> ```
> [+] Building 0.0s (0/0)  docker:default
> [+] Building 1.8s (5/9)                                                                                         docker:default
>  => [abi internal] load build definition from Dockerfile                                                                  0.0s
>  => => transferring dockerfile: 205B                                                                                      0.0s
>  => [abi internal] load metadata for docker.io/library/python:3.9                                                         0.6s
>  => [abi internal] load .dockerignore                                                                                     0.0s
>  => => transferring context: 2B                                                                                           0.0s
>  => [abi 1/5] FROM docker.io/library/python:3.9@sha256:dd8b65c39a729f946398d2e03a3e6defc8c0cfec409b9f536200634ad6408b54   0.0s
>  => ERROR [abi internal] load build context                                                                               1.1s
>  => => transferring context: 57.28MB                                                                                      1.1s
> ------
>  > [abi internal] load build context:
> ------
> failed to solve: archive/tar: unknown file mode ?rwxr-xr-x
> ```
> 
> I was able to solve it using the last comment of https://stackoverflow.com/questions/78523506/docker-error-failed-to-solve-archive-tar-unknown-file-mode-rwxr-xr-x - I needed to delete the automatically created .venv folder after every previous docker build. Maybe that is something that can be done automatically.
> 
> Unfortunately, I ran into a different challenge.
> 
> ```
>  ✔ Network 2608naasabi_default  Created                                                                         0.0s 
>  ✔ Container 2608naasabi-abi-1  Created                                                                         0.0s 
> Attaching to abi-1
> abi-1  | Creating virtualenv src in /app/.venv
> abi-1  | Command not found: chat-single-assistant
> abi-1 exited with code 1
> ```
> 
> Any ideas on where it goes of?

Yes! This command does not exist anymore. Since, you open this issue, we added more agents and now you can start with "make" to start chatting with the default agent. You can also pick any agent available from the list in the README 4. : https://github.com/jupyter-naas/abi?tab=readme-ov-file#getting-started 
What would you like to do? Do you already have something in mind?
