### ISSUE TITLE
Ability to List Naas Workspaces

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/abi#293]
Currently, there is no direct functionality to list all Naas workspaces for a user. It would be beneficial to have a feature that allows users to view all their Naas workspaces directly through the assistant. This would enhance user experience by providing easy access to workspace information.

**Comment by Dr0p42** [comment]
@FlorentLvr with the supervisor assistant it seems that I have issues listing naas workspaces. But it might be expected be seeing the tools connected to it.

**Comment by FlorentLvr** [comment]
> @FlorentLvr with the supervisor assistant it seems that I have issues listing naas workspaces. But it might be expected be seeing the tools connected to it.

Supervisor was not aware of this feature. It's fixed now as i created a dynamic system prompt with tools from agents
