### ISSUE TITLE
Youtube_Extract_Clip_and_Generate_Content_Ideas

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/abi#5]
User journey to be defined @jravenel

**Comment by FlorentLvr** [comment]
@jravenel, this template is integrated in: abi/models/content-engine/YouTube_Extract_Clip_and_Generate_Content_Ideas.ipynb
As the webhook feature is not working yet, you can copy/paste the message in the input bar of your chat. Let me know if you have any questions!
