### ISSUE TITLE
Build the demo scenario as first class citizen 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/abi#60]
The idea is to plug this demo scenario into the code base so that anyone can have a full picture of the functionalities.

**Comment by FlorentLvr** [comment]
Google Sheets: https://docs.google.com/spreadsheets/d/1wuG6t4fzVKra0pTm6NzE1RsiT_NOIPPjwRN3niBQ2lY/edit#gid=800734934

- Content: https://public.naas.ai/YWJpLTJEZGVtby00MG5hYXMtMkVhaQ==/asset/8a5c740290f7fa43cec3a7538f261ddf7f9d824273d58bf986f4731e5df2
- Growth: https://public.naas.ai/YWJpLTJEZGVtby00MG5hYXMtMkVhaQ==/asset/c83e00f7be557be6d036a0c884cea29d89b06fc32764e81784af0f7feb1c
- Sales:  https://public.naas.ai/YWJpLTJEZGVtby00MG5hYXMtMkVhaQ==/asset/78ddf7cde7b71fa293c3ccbc35722154fe2fa76628f6097dc8cca5c3e180

**Comment by FlorentLvr** [comment]
@jravenel

**Comment by FlorentLvr** [comment]
@jravenel, to be replaced in production

**Comment by FlorentLvr** [comment]
Plugin integrated in workspace 👍
